### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by PickledKitty** [SN-RECIT-formation-a-distance/moodle-atto_htmlbootstrapeditor#1]
Hi,

Are there more robust installation instructions available?
Directory to install it into is, I assume, /lib/editor/atto/plugins?

But how do you then get the plugin to appear in the atto plugins list in order to add it to the atto toolbar on the settings page: https://.../admin/settings.php?section=editorsettingsatto

I notice there is a text file 'how-to-compile-yui.txt', but it assumes you are on Windows, using wamp. What about Linux?

Your help would be greatly appreciated.

**Comment by gustavobazzo** [comment]
Dear @PickledKitty,

If you install this plugin through Moodle interface, it will automatically place the plugin in the Atto toolbar.
