### ISSUE TITLE
Update user instructions in plugin description

### ISSUE THREAD

**Issue by germanvaleroelizondo** [SN-RECIT-formation-a-distance/moodle-atto_htmlbootstrapeditor#4]
PLEASE Update user instructions in plugin description in https://moodle.org/plugins/atto_htmlbootstrapeditor

'After installing this plugin, it is necessary to place it in the Atto bar.' is NOT a user friendly instruction.

Please describe the steps needed:

Go to site administration > Plugins > Text editors > Atto toolbar settings 

In the Toolbar configuration text box write ...
...
... and save the changes.

You will then be able to use this toll from ...

Thanks in advance 

...

Thanks in advance

**Comment by gustavobazzo** [comment]
Hello @germanvaleroelizondo 

Thank you for your comment.

This issue was fixed with [2402d05](https://github.com/SN-RECIT-formation-a-distance/moodle-atto_htmlbootstrapeditor/commit/2402d054a51fdec0b192e8d84a0186e3e99c3dba)
